vintasoftware/tapioca-wrapper

.travis.yml
tox.ini

Need to add the badges to README! Every cool project needs it.
Access https://travis-ci.org/ and https://coveralls.io/ to get them

Configuring travis and coveralls

---

README.md
docs/newflavour.md
tapioca/__init__.py
tapioca/exceptions.py
tapioca/tapioca.py
tests/test_tapioca.py

- Explicit ```pages()``` call for automatic page fetching
- Support for "len()"
- Access to data attributes on executor
#4 #5

Automatic page iteration now needs explicit "pages()" call

---

docs/changelog.md
docs/index.md

Adding change log to documentation

---

docs/contributors.md
tapioca/tapioca.py
tests/test_tapioca.py

Hello :),
I saw the issue https://github.com/vintasoftware/tapioca-wrapper/issues/28 and I tryied to implement the change. Could you verify if this was what you were thinking? And if not, could you please help me to make the necessary changes?
Cheers,

Support "max_pages" and "max_items" on "pages" generator

---

docs/quickstart.md

I just updated the pages method documentation https://github.com/vintasoftware/tapioca-wrapper/issues/40. It is ok? Should I change anything?
Regards,

Document "max_pages" and "max_items" on "pages" method

---

tapioca/tapioca.py

fix default api_param

---

tapioca/adapters.py
tapioca/tapioca.py

pass request_method to get_request_kwargs make it possible to adapter instance to make some decision based on request_method, such as set aditional headers.

Request method

---

docs/flavours.md

Fix typo in Harvest name in docs

---

docs/flavours.md

I have added the package to PyPI(https://pypi.python.org/pypi/tapioca-crunchbase/0.1)

Adding CrunchBase to flavours

---

docs/about.md
docs/changelog.md
docs/newflavour.md
docs/quickstart.md

Correcting bunch of spelling mistakes in documentation!

Fixing spelling errors

---

setup.py

Tying dependencies versions

---

docs/source/conf.py
docs/source/index.rst
docs/source/newflavour.rst
docs/source/serializers.rst

Adapter Docs

---

docs/source/exceptions.rst

Documenting on how to deal with exceptions

---

README.md

Adding reference to cookiecutter in the README

---

tests/test_tapioca.py

Fixing assert raises test warning

---

tapioca/exceptions.py
tests/test_exceptions.py

Renaming exception status attribute to status_code

---

tapioca/tapioca.py
tests/test_tapioca.py

Adding status_code method to executor

---

docs/source/serializers.rst
tapioca/adapters.py
tapioca/serializers.py
tests/test_serializers.py
tests/test_tapioca.py

Serialization

---

docs/source/flavours.rst

Wrapper for [Toggl](https://toggl.com/) :smile_cat:

Add a new flavour for Toggl to the mix

---

docs/source/adapter.rst
docs/source/quickstart.rst
tapioca/adapters.py
tapioca/tapioca.py
tests/client.py
tests/test_tapioca.py

It allows automatic refresh of access token for services that implement refresh tokens: https://github.com/vintasoftware/tapioca-wrapper/issues/13

Refresh token support

---

tapioca/tapioca.py

Addressing #85 with this patch.

print OrderedDict nicely

---

docs/source/exceptions.rst
docs/source/newflavour.rst
docs/source/quickstart.rst
docs/source/serializers.rst

I'm digging into tapioca for a project at work and really like it. Your documentation is far more complete and helpful than any I've seen from similar wrapper projects! With that in mind, I did some cleanup of the grammar and spelling. Cheers!

Grammar and spelling fixes

---

setup.py

Hello there,
First, congrats for build this project, tapioca is a really cool lib.
I'm sending this PR to change requests dependency, my stack project is using requests 2.10. 
Guess many people are using requests>2.7, maybe should be better define just the minimal requirement as 2.6 version.

Improving setup.py for update requests lib

---

docs/source/adapter_class.rst
docs/source/buildingawrapper.rst
docs/source/changelog.rst
docs/source/features.rst
tapioca/adapters.py
tapioca/tapioca.py
tests/client.py
tests/test_tapioca.py

Changes the refresh_authentication process and gives access to data returned from it.
@georgeyk I think you will like this :)

Token refresh process

---

tapioca/tapioca.py

Added missing options header method.

Updated tapioca.py

---

.travis.yml
setup.py
tox.ini

Use requests[security] instead of requests

---

docs/source/quickstart.rst

fix typo in documentation

---

docs/source/changelog.rst
tapioca/__init__.py
tapioca/tapioca.py
tests/client.py
tests/test_tapioca.py

Using fix n. 2 discussed at: https://stackoverflow.com/a/50888571

Fix pickle of tapioca objects

---

.github/workflows/build-release.yml
.github/workflows/tests.yml
Makefile
README.md
docs/source/changelog.rst
tapioca/__init__.py

Create GHA for release on pypi

Create GHA for release
